// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthControllerHackclubAuthCallbackData, AuthControllerHackclubAuthCallbackResponses, AuthControllerHackclubAuthData, AuthControllerHackclubAuthResponses, ChatControllerGetModelsData, ChatControllerGetModelsResponses, ChatControllerSendMessageData, ChatControllerSendMessageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class auth {
    /**
     * Signin with Hackclub Auth
     *
     * Redirect the user to the Hackclub Auth sign up page,  after the user authorizes your app, they will be redirected to the redirect url you provide with an authorization code
     */
    public static authControllerHackclubAuth<ThrowOnError extends boolean = false>(options: Options<AuthControllerHackclubAuthData, ThrowOnError>): RequestResult<AuthControllerHackclubAuthResponses, unknown, ThrowOnError> {
        return (options.client ?? client).get<AuthControllerHackclubAuthResponses, unknown, ThrowOnError>({ url: '/api/auth/hackclubauth', ...options });
    }
    
    /**
     * Exchange your code, and get user data
     *
     * Exchange your code and get user data
     */
    public static authControllerHackclubAuthCallback<ThrowOnError extends boolean = false>(options: Options<AuthControllerHackclubAuthCallbackData, ThrowOnError>): RequestResult<AuthControllerHackclubAuthCallbackResponses, unknown, ThrowOnError> {
        return (options.client ?? client).get<AuthControllerHackclubAuthCallbackResponses, unknown, ThrowOnError>({ url: '/api/auth/hackclubauth/callback', ...options });
    }
}

export class chat {
    /**
     * Get all models
     *
     * Get all models from Hackclub ai proxy
     */
    public static chatControllerGetModels<ThrowOnError extends boolean = false>(options?: Options<ChatControllerGetModelsData, ThrowOnError>): RequestResult<ChatControllerGetModelsResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<ChatControllerGetModelsResponses, unknown, ThrowOnError>({ url: '/api/chat/models', ...options });
    }
    
    /**
     * Send a message
     *
     * Chat with the ai assistance
     */
    public static chatControllerSendMessage<ThrowOnError extends boolean = false>(options: Options<ChatControllerSendMessageData, ThrowOnError>): RequestResult<ChatControllerSendMessageResponses, unknown, ThrowOnError> {
        return (options.client ?? client).post<ChatControllerSendMessageResponses, unknown, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/chat/send',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
