// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:2832' | (string & {});
};

export type AuthResponseDto = {
    /**
     * User name from slack
     */
    name: string;
    /**
     * User profile picture from slack
     */
    profilePicture: string;
    /**
     * User slack id
     */
    slackId: string;
    /**
     * access token to send ai request
     */
    access_token: string;
};

export type ModelArchitectureDto = {
    modality: string;
    input_modalities: Array<string>;
    output_modalities: Array<string>;
    tokenizer: string;
    instruct_type: string | null;
};

export type ModelPricingDto = {
    prompt: number;
    completion: number;
    image_output?: number;
    web_search?: number;
    input_cache_read?: number;
};

export type ModelResponseDto = {
    id: string;
    canonical_slug: string;
    hugging_face_id: string | null;
    name: string;
    created: number;
    description: string;
    context_length: number;
    architecture: ModelArchitectureDto;
    pricing: ModelPricingDto;
};

export type ModelConfigDto = {
    modelName: string;
    temperatureOrCreativity: number;
    responseDetailLevel: 'short' | 'balanced' | 'detailed';
};

export type UserDataDto = {
    userIdentify: string;
    customInstruction: string;
};

export type MessageDto = {
    role: 'system' | 'user' | 'assistant';
    content: string;
};

export type SendMessageDto = {
    modelConfig: ModelConfigDto;
    userData: UserDataDto;
    messages: Array<MessageDto>;
};

export type ChatResponseUsageDto = {
    inputToken: number;
    outputToken: number;
};

export type ChatResponseObjectDto = {
    role: string;
    content: string;
};

export type ChatResponseDto = {
    usage: ChatResponseUsageDto;
    reasoning: string | null;
    response: ChatResponseObjectDto;
};

export type AuthControllerHackclubAuthData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The URI to redirect the user to after authentication
         */
        redirect_uri: string;
    };
    url: '/api/auth/hackclubauth';
};

export type AuthControllerHackclubAuthResponses = {
    200: unknown;
};

export type AuthControllerHackclubAuthCallbackData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The URI to redirect the user to after authentication
         */
        redirect_uri: string;
        /**
         * The code return from the redirect from Hackclub Auth oauth page
         */
        code: string;
    };
    url: '/api/auth/hackclubauth/callback';
};

export type AuthControllerHackclubAuthCallbackResponses = {
    200: AuthResponseDto;
};

export type AuthControllerHackclubAuthCallbackResponse = AuthControllerHackclubAuthCallbackResponses[keyof AuthControllerHackclubAuthCallbackResponses];

export type ChatControllerGetModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/models';
};

export type ChatControllerGetModelsResponses = {
    200: ModelResponseDto;
};

export type ChatControllerGetModelsResponse = ChatControllerGetModelsResponses[keyof ChatControllerGetModelsResponses];

export type ChatControllerSendMessageData = {
    body: SendMessageDto;
    path?: never;
    query?: never;
    url: '/api/chat/send';
};

export type ChatControllerSendMessageResponses = {
    200: ChatResponseDto;
};

export type ChatControllerSendMessageResponse = ChatControllerSendMessageResponses[keyof ChatControllerSendMessageResponses];
